#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/hardening
- name: Disable root login via SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: Enforce password expiration (90 days)
  lineinfile:
    path: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'

- name: Install auditd
  package:
    name: auditd
    state: present

- name: Ensure auditd is running
  service:
    name: auditd
    state: started
    enabled: yes
